import { createServerClient } from "@supabase/ssr";
import { NextResponse, type NextRequest } from "next/server";
import { SUPABASE_URL, SUPABASE_ANON_KEY } from "@/lib/supabase/config";

const PUBLIC_PATHS = ["/login", "/forgot-password"];

export async function proxy(request: NextRequest) {
  let response = NextResponse.next({ request });

  const supabase = createServerClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },
        setAll(cookiesToSet) {
          for (const { name, value } of cookiesToSet) {
            request.cookies.set(name, value);
          }
          response = NextResponse.next({ request });
          for (const { name, value, options } of cookiesToSet) {
            response.cookies.set(name, value, options);
          }
        },
      },
    },
  );

  const {
    data: { user },
  } = await supabase.auth.getUser();

  const isPublicPath = PUBLIC_PATHS.some((path) =>
    request.nextUrl.pathname.startsWith(path),
  );

  if (!user && !isPublicPath) {
    const url = request.nextUrl.clone();
    url.pathname = "/login";
    return NextResponse.redirect(url);
  }

  if (user && request.nextUrl.pathname === "/login") {
    const url = request.nextUrl.clone();
    url.pathname = "/";
    return NextResponse.redirect(url);
  }

  return response;
}

// Anything listed here is served without an auth check. Getting this list
// wrong is subtle and expensive: a signed-out request for an excluded-by-
// mistake path gets a 307 to /login instead of the file, and the browser
// reports that as a confusing, unrelated-sounding error.
//
// Specifically, `/sw.js` MUST be excluded. A service worker script served
// behind a redirect is rejected outright by the browser with "The script
// resource is behind a redirect, which is disallowed." — the app's first
// load is always signed out, so registration failed every single time.
//
// `/manifest.webmanifest` (generated by app/manifest.ts — note it is NOT
// manifest.json, which is what this matcher used to name) and the
// generated icon routes must be excluded for the same reason, otherwise
// the PWA install prompt has no manifest or icons to read.
export const config = {
  matcher: [
    "/((?!_next/static|_next/image|favicon.ico|sw\\.js|manifest\\.webmanifest|robots\\.txt|icon|icon-192|icon-512|apple-icon|icons/|.*\\.(?:svg|png|jpg|jpeg|gif|webp|ico|webmanifest)$).*)",
  ],
};
